# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('main_text', models.TextField()),
                ('post_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
